function getAllCities(){
   let cidades = [{id: "0", label: "Selecione o Município"},
                 {id: "1", label: "Abadia"},
                 {id: "3", label: "Abadiânia"},
                 {id: "28", label: "Acreúna"},
                 {id: "31", label: "Adelândia"},
                 {id: "57", label: "Água Fria de Goiás"},
                 {id: "58", label: "Água Limpa"},
                 {id: "72", label: "Águas Lindas de Goiás"},
                 {id: "109", label: "Alexânia"},
                 {id: "125", label: "Aloândia"},
                 {id: "152", label: "Alto Horizonte"},
                 {id: "157", label: "Alto Paraíso de Goiás"},
                 {id: "180", label: "Alvorada do Norte"},
                 {id: "189", label: "Amaralina"},
                 {id: "197", label: "Americano do Brasil"},
                 {id: "202", label: "Amorinópolis"},
                 {id: "217", label: "Anápolis"},
                 {id: "243", label: "Anhanguera"},
                 {id: "246", label: "Anicuns"},
                 {id: "269", label: "Aparecida de Goiânia"},
                 {id: "270", label: "Aparecida do Rio Doce"},
                 {id: "281", label: "Aporé"},
                 {id: "304", label: "Araçu"},
                 {id: "306", label: "Aragarças"},
                 {id: "307", label: "Aragoiânia"},
                 {id: "316", label: "Araguapaz"},
                 {id: "373", label: "Arenópolis"},
                 {id: "398", label: "Aruanã"},
                 {id: "426", label: "Aurilândia"},
                 {id: "437", label: "Avelinópolis"},
                 {id: "459", label: "Baliza"},
                 {id: "566", label: "Bela Vista de Goiás"},
                 {id: "665", label: "Bom Jardim de Goiás"},
                 {id: "676", label: "Bom Jesus de Goiás"},
                 {id: "703", label: "Bonfinópolis"},
                 {id: "712", label: "Bonópolis"},
                 {id: "754", label: "Brazabrantes"},
                 {id: "774", label: "Britânia"},
                 {id: "794", label: "Buriti Alegre"},
                 {id: "796", label: "Buriti de Goiás"},
                 {id: "801", label: "Buritin&Aocute;polis"},
                 {id: "816", label: "Cabeceiras"},
                 {id: "833", label: "Cachoeira Alta"},
                 {id: "835", label: "Cachoeira de Goiás"},
                 {id: "842", label: "Cachoeira Dourada"},
                 {id: "858", label: "Caçu"},
                 {id: "873", label: "Caiapônia"},
                 {id: "900", label: "Caldas Novas"},
                 {id: "901", label: "Caldazinha"},
                 {id: "933", label: "Campestre de Goiás"},
                 {id: "942", label: "Campinaçu"},
                 {id: "947", label: "Campinorte"},
                 {id: "950", label: "Campo Alegre de Goiás"},
                 {id: "16446", label: "Campo Limpo de Goiás"},
                 {id: "980", label: "Campos Belos"},
                 {id: "990", label: "Campos Verdes"},
                 {id: "1125", label: "Carmo do Rio Verde"},
                 {id: "1164", label: "Castelândia"},
                 {id: "1171", label: "Catalão"},
                 {id: "1187", label: "Caturaí"},
                 {id: "1192", label: "Cavalcante"},
                 {id: "1215", label: "Ceres"},
                 {id: "1227", label: "Cezarina"},
                 {id: "1239", label: "Chapadão do Ceu"},
                 {id: "1262", label: "Cidade Ocidental"},
                 {id: "1281", label: "Cocalzinho de Goiás"},
                 {id: "1295", label: "Colinas do Sul"},
                 {id: "1402", label: "Corrego do Ouro"},
                 {id: "1411", label: "Corumba de Goiás"},
                 {id: "1412", label: "Corumbaíba"},
                 {id: "1446", label: "Cristalina"},
                 {id: "1448", label: "Cristianópolis"},
                 {id: "1453", label: "Crixás"},
                 {id: "1456", label: "Cromínia"},
                 {id: "1482", label: "Cumari"},
                 {id: "1511", label: "Damianópolis"},
                 {id: "1513", label: "Damolândia"},
                 {id: "1518", label: "Davinópolis"},
                 {id: "1548", label: "Diorama"},
                 {id: "1559", label: "Divinópolis de Goiás"},
                 {id: "1612", label: "Doverlândia"},
                 {id: "1624", label: "Edealina"},
                 {id: "1625", label: "Edéia"},
                 {id: "1704", label: "Estrela do Norte"},
                 {id: "1720", label: "Faina"},
                 {id: "1736", label: "Fazenda Nova"},
                 {id: "1771", label: "Firminópolis"},
                 {id: "1781", label: "Flores de Goiás"},
                 {id: "1799", label: "Formosa"},
                 {id: "1804", label: "Formoso"},
                 {id: "16448", label: "Gameleira de Goiás"},
                 {id: "1900", label: "Goianápolis"},
                 {id: "16443", label: "Goianápolis"},
                 {id: "1901", label: "Goiandira"},
                 {id: "1902", label: "Goianésia"},
                 {id: "1904", label: "Goiânia"},
                 {id: "1906", label: "Goianira"},
                 {id: "1908", label: "Goiás"},
                 {id: "1910", label: "Goiatuba"},
                 {id: "1918", label: "Gouvelândia"},
                 {id: "1972", label: "Guapó"},
                 {id: "1985", label: "Guaraíta"},
                 {id: "1992", label: "Guarani de Goiás"},
                 {id: "2009", label: "Guarinos"},
                 {id: "2029", label: "Heitoraí"},
                 {id: "2037", label: "Hidrolândia"},
                 {id: "2038", label: "Hidrolina"},
                 {id: "2050", label: "Iaciara"},
                 {id: "2159", label: "Inaciolândia"},
                 {id: "2172", label: "Indiara"},
                 {id: "2185", label: "Inhumas"},
                 {id: "2191", label: "Ipameri"},
                 {id: "16447", label: "Ipiranga de Goiás"},
                 {id: "2213", label: "Iporá"},
                 {id: "2250", label: "Israelândia"},
                 {id: "2259", label: "Itaberaí"},
                 {id: "2280", label: "Itaguari"},
                 {id: "2281", label: "Itaguaru"},
                 {id: "2293", label: "Itajá"},
                 {id: "2322", label: "Itapaci"},
                 {id: "2346", label: "Itapirapuã"},
                 {id: "2364", label: "Itapuranga"},
                 {id: "2375", label: "Itaruma"},
                 {id: "2388", label: "Itauçu"},
                 {id: "2407", label: "Itumbiara"},
                 {id: "2422", label: "Ivolândia"},
                 {id: "2474", label: "Jandaia"},
                 {id: "2496", label: "Jaraguá"},
                 {id: "2513", label: "Jataí"},
                 {id: "2523", label: "Jaupaci"},
                 {id: "2541", label: "Jesupólis"},
                 {id: "2579", label: "Joviânia"},
                 {id: "2623", label: "Jussara"},
                 {id: "2726", label: "Leopoldo de Bulhões"},
                 {id: "2782", label: "Luziânia"},
                 {id: "2823", label: "Mairipotaba"},
                 {id: "2836", label: "Mambaí"},
                 {id: "2867", label: "Mararosa"},
                 {id: "2941", label: "Marzagão"},
                 {id: "2977", label: "Matrinchã"},
                 {id: "2985", label: "Maurilândia"},
                 {id: "3020", label: "Mimoso de Goiás"},
                 {id: "3022", label: "Minaçu"},
                 {id: "3027", label: "Mineiros"},
                 {id: "3066", label: "Moiporá"},
                 {id: "3087", label: "Monte Alegre de Goiás"},
                 {id: "3119", label: "Montes Claros de Goiás"},
                 {id: "3121", label: "Montividiu"},
                 {id: "3122", label: "Montividiu do Norte"},
                 {id: "3132", label: "Morrinhos"},
                 {id: "3135", label: "Morro Agudo de Goiás"},
                 {id: "3148", label: "Mossâmedes"},
                 {id: "3152", label: "Mozarlândia"},
                 {id: "3181", label: "Mutunópolis"},
                 {id: "3205", label: "Nazário"},
                 {id: "3208", label: "Nerópolis"},
                 {id: "3219", label: "Niquelândia"},
                 {id: "3240", label: "Nova América"},
                 {id: "3245", label: "Nova Aurora"},
                 {id: "3260", label: "Nova Crixás"},
                 {id: "3272", label: "Nova Glória"},
                 {id: "3279", label: "Nova Iguaçu de Goiás"},
                 {id: "3316", label: "Nova Roma"},
                 {id: "3335", label: "Nova Veneza"},
                 {id: "3344", label: "Novo Brasil"},
                 {id: "3347", label: "Novo Gama"},
                 {id: "3363", label: "Novo Planalto"},
                 {id: "3407", label: "Orizona"},
                 {id: "3435", label: "Ouro Verde de Goiás"},
                 {id: "3440", label: "Ouvidor"},
                 {id: "3449", label: "Padre Bernardo"},
                 {id: "3465", label: "Palestina de Goiás"},
                 {id: "3488", label: "Palmeiras de Goiás"},
                 {id: "3492", label: "Palmelo"},
                 {id: "3493", label: "Palminópolis"},
                 {id: "3500", label: "Panamá"},
                 {id: "3536", label: "Paranaiguara"},
                 {id: "3552", label: "Paraúna"},
                 {id: "3695", label: "Perolândia"},
                 {id: "3702", label: "Petrolina de Goiás"},
                 {id: "3722", label: "Pilar de Goiás"},
                 {id: "3763", label: "Piracanjuba"},
                 {id: "3779", label: "Piranhas"},
                 {id: "3793", label: "Pirenópolis"},
                 {id: "3794", label: "Pires do Rio"},
                 {id: "3810", label: "Planaltina"},
                 {id: "3851", label: "Pontalina"},
                 {id: "3871", label: "Porangatu"},
                 {id: "3876", label: "Porteirão"},
                 {id: "3880", label: "Portelândia"},
                 {id: "3918", label: "Posse"},
                 {id: "3978", label: "Professor Jamil"},
                 {id: "4018", label: "Quirinópolis"},
                 {id: "4089", label: "Rialma"},
                 {id: "4090", label: "Rianápolis"},
                 {id: "4172", label: "Rio Quente"},
                 {id: "4177", label: "Rio Verde"},
                 {id: "4220", label: "Rubiataba"},
                 {id: "4271", label: "Sanclerlândia"},
                 {id: "4282", label: "Santa Bárbara de Goiás"},
                 {id: "4305", label: "Santa Cruz de Goiás"},
                 {id: "4319", label: "Santa Fé de Goiás"},
                 {id: "4331", label: "Santa Helena de Goiás"},
                 {id: "4337", label: "Santa Isabel"},
                 {id: "4387", label: "Santa Rita do Araguaia"},
                 {id: "4389", label: "Santa Rita do Novo Destino"},
                 {id: "4397", label: "Santa Rosa de Goiás"},
                 {id: "4409", label: "Santa Tereza de Goiás"},
                 {id: "4415", label: "Santa Terezinha de Goiás"},
                 {id: "4465", label: "Santo Antônio da Barra"},
                 {id: "4469", label: "Santo Antônio de Goiás"},
                 {id: "4478", label: "Santo Antônio do Descoberto"},
                 {id: "4565", label: "Sao Francisco de Goiás"},
                 {id: "4615", label: "Sao Joao da Paraúna"},
                 {id: "4730", label: "Sao Luis de Montes Belos"},
                 {id: "4736", label: "Sao Luiz do Norte"},
                 {id: "4757", label: "Sao Miguel do Araguaia"},
                 {id: "4763", label: "Sao Miguel do Passa Quatro"},
                 {id: "4769", label: "Sao Patrício"},
                 {id: "4824", label: "Sao Simão"},
                 {id: "4879", label: "Senador Canedo"},
                 {id: "4930", label: "Serranópolis"},
                 {id: "4960", label: "Silvânia"},
                 {id: "4971", label: "Simolândia"},
                 {id: "4979", label: "Sítio d'Abadia"},
                 {id: "5079", label: "Taquaral de Goiás"},
                 {id: "5122", label: "Teresina de Goiás"},
                 {id: "5125", label: "Terezópolis de Goiás"},
                 {id: "5202", label: "Três Ranchos"},
                 {id: "5207", label: "Trindade"},
                 {id: "5215", label: "Trombas"},
                 {id: "5249", label: "Turvânia"},
                 {id: "5250", label: "Turvelândia"},
                 {id: "5274", label: "Uirapuru"},
                 {id: "5303", label: "Uruaçu"},
                 {id: "5304", label: "Uruana"},
                 {id: "5321", label: "Urutaí"},
                 {id: "5337", label: "Valparaiso de Goiás"},
                 {id: "5351", label: "Varjão"},
                 {id: "5397", label: "Vianópolis"},
                 {id: "5401", label: "Vicentinópolis"},
                 {id: "5413", label: "Vila Boa"}]
   return cidades;
 }